language: node_js
node_js:
- 4.4.5
env:
  - NODE_ENV=prod
  - NODE_ENV=dev
cache:
  directories:
    - node_modules
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
- npm install -g babel
- npm install -g webpack
- npm install -g webpack-dev-server
- npm install -g eslint
- npm install
- sudo pip install -r requirements.txt
script:
- npm run lint:travis
- npm run test
- pybot test.robot
notifications:
  email:
  - stollenwerk@kitconcept.com
